stages:
  - deploy
  - test

pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx furo myst-parser sphinx_rtd_theme
  script:
    - sphinx-apidoc -f -o docs/modules ./src
    - make html
  after_script:
    - mv _doc/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

format:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - python -m pip install yapf
  script:
    - yapf -ri ./src ./tests


test:
  stage: test
  image: ubuntu:20.04
  script:
    - pytest --junitxml=report.xml
  before_script:
    - apt-get update && apt-get install python3 --no-install-recommends -y
    - python3 -m venv venv && source venv/bin/activate
    - pip install -r requirements_slim.txt
    - pip install pytest
    - pip install -e . 
  artifacts:
    when: always
    reports:
      junit: report.xml