stages:
  - clean
  - test
  - deploy


format:
  stage: clean
  image: python:3.9-slim
  before_script:
    - python -m pip install yapf toml
  script:
    - yapf -ri ./src ./tests


test:
  stage: test
  image: ubuntu:20.04
  script:
    - tox -e py38
  before_script:
    - apt-get update && apt-get install python3 python3.8-venv --no-install-recommends -y
    - python3 -m venv venv && source venv/bin/activate
    - pip install -r requirements_setup.txt
  artifacts:
    when: always
    reports:
      junit: report.xml


pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    # - apt-get update && apt-get install make --no-install-recommends -y
    - pip install -r requirements_setup.txt
  script:
    - tox -e docs
  after_script:
    - mv _doc/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
